SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTATISTICA;
CREATE DATABASE DBESTATISTICA;
USE DBESTATISTICA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, SEXO CHAR(1)
);

CREATE TABLE ESTATISTICA (	
	HOMEM INT
	, MULHER INT
);


INSERT INTO ESTATISTICA(HOMEM,MULHER) VALUES (0,0);

DELIMITER $$

-- Apos inserir
CREATE TRIGGER TR_AI_PESSOA AFTER INSERT ON PESSOA FOR EACH ROW
BEGIN
	IF NEW.SEXO = 'M' THEN
		UPDATE ESTATISTICA SET HOMEM = HOMEM+1;
    ELSEIF NEW.SEXO = 'F' THEN
    UPDATE ESTATISTICA SET MULHER = MULHER+1;
	END IF;
END $$

-- Verificar sexo
CREATE TRIGGER TR_BI_PESSOA BEFORE INSERT ON PESSOA FOR EACH ROW
BEGIN
	IF(NEW.SEXO NOT IN ('M','F') OR NEW.SEXO IS NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SEXO INVALIDO';
    END IF;
END $$

-- Apos deletar
CREATE TRIGGER TR_AD_PESSOA AFTER DELETE ON PESSOA FOR EACH ROW
BEGIN
	IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA SET HOMEM = HOMEM-1;
    ELSEIF OLD.SEXO = 'F' THEN
    UPDATE ESTATISTICA SET MULHER = MULHER-1;
	END IF;
END $$


-- Apos update
CREATE TRIGGER TR_AU_PESSOA AFTER UPDATE ON PESSOA FOR EACH ROW
BEGIN
	IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA SET HOMEM = HOMEM-1;
    ELSEIF OLD.SEXO = 'F' THEN
		UPDATE ESTATISTICA SET HOMEM = MULHER-1;
	END IF;

	IF NEW.SEXO = 'M' THEN
		UPDATE ESTATISTICA SET HOMEM = HOMEM+1;
    ELSEIF NEW.SEXO = 'F' THEN
		UPDATE ESTATISTICA SET MULHER = MULHER+1;
	END IF;
END $$

-- Verificar apos update
CREATE TRIGGER TR_BU_PESSOA BEFORE UPDATE ON PESSOA FOR EACH ROW
BEGIN
	IF(NEW.SEXO NOT IN ('M','F') OR NEW.SEXO IS NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SEXO INVALIDO';
    END IF;
END $$
DELIMITER ;


INSERT INTO PESSOA(NOME,SEXO) VALUES ('LEO', 'M');
INSERT INTO PESSOA(NOME,SEXO) VALUES ('ALICE', 'F');
DELETE FROM PESSOA WHERE SEXO = 'F';
SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA;

UPDATE PESSOA SET SEXO = 'F' WHERE NOME = 'LEO';
